on:
  pull_request_target:
    branches:
    - main

jobs:
  label-release:
    if: ${{ startsWith(github.event.pull_request.title, 'release:') }}
    runs-on: ubuntu-22.04
    steps:
    - run: echo this is a release PR
    - run: gh pr edit ${{ github.event.pull_request.number }} --add-label release
env:
  NPM_CONFIG_REGISTRY: https://time-machines-npm.sealsecurity.io/
  NPM_CONFIG_//time-machines-npm.sealsecurity.io/:_authToken: '2023-07-06T11:27:10.524000Z'
